#version: '3'
#
#services:
#  potgres:
#    container_name: db-graphql-demo
#    image: postgres
#    environment:
#      - POSTGRES_USER: "postgres"
#      - POSTGRES_PASSWORD: "postgres"
#      - PGDATE: /data/demo-graphql-postgres
#    volumes:
#      - postgres:/data/demo-graphql-postgres
#    networks:
#      - demo_graphql_net
#    ports:
#    - '5432:5432'
#    expose:
#      - "5432"
#    restart: on-failure
#
#  web:
#    build: .
#    command: bash -c "python manage.py collectstatic --no-input && python manage.py runserver 0.0.0.0:2222"
#    container_name: demo_graphql
#    restart: always
#    volumes:
#      - .:/demo_graphql
#    expose:
#      - "2222"
#    ports:
#      - "2222:2222"
#    environment:
##      - POSTGRES_DB: demo_graphql_db
#      - POSTGRES_USER: "postgres"
#      - POSTGRES_PASSWORD: "postgres"
#    depends_on:
#      - potgres
#    networks:
#      - demo_graphql_net
#
#networks:
#  demo_graphql_net:
#    driver: bridge

version: "3"

services:
  web:
    build:
      context: .
    ports:
      - "2222:2222"
    container_name: demo_graphql
    restart: always
    volumes:
      - .:/demo_graphql
    expose:
      - "2222"
    command: >
      sh -c "python manage.py runserver 0.0.0.0:2222"